### ISSUE TITLE
Missng data in mRNA?

### ISSUE THREAD

**Issue by Casperqian** [yangheng95/OmniGenome-SupplementaryMaterials#1]
Hi, I noticed that there is no validation data available in the `./benchmark/rgb/RNA-mRNA/` directory. Maybe you forget to upload it?

**Comment by yangheng95** [comment]
I collected the data from the Kaggle competition, where only two stages got the data. The final testing dataset is private. So I made data from Phase 1 and 2 to be training and testing datasets respectively. Therefore, there is no specific validation data.

**Comment by Casperqian** [comment]
Thank you!
